apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
      - name: argocd-test
        image: platof/argocd-test-app:4.2.2-sha.40506be
        ports:
        - containerPort: 8080
