apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      imagePullSecrets:
      - name: ghcr-creds
      containers:
      - name: argocd-test
        image: ghcr.io/platof/argocd-update-test/argocd-test-app:4.2.2-sha.a2f4919
        ports:
        - containerPort: 8080
