apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
      - name: argocd-test
        image: platof/argocd-test-app:1d8ea2da16ef317a66805d78ff03b6ce563fec06
        ports:
        - containerPort: 8080
