apiVersion: batch/v1
kind: Job
metadata:
  name: inject-image-pull-secret
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: default
      containers:
        - name: copy-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Cloning image pull secret from argocd namespace..."
              kubectl get secret ghcr-creds -n argocd -o yaml \
              | sed "s/namespace: argocd/namespace: $ARGOCD_APP_NAMESPACE/" \
              | kubectl apply -n $ARGOCD_APP_NAMESPACE -f -
          env:
            - name: ARGOCD_APP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      restartPolicy: OnFailure
