name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history in case you want to tag

    - name: Extract version from package.json
      id: pkg
      run: |
        VERSION=$(jq -r .version package.json)
        echo "Extracted version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t your-docker-user/your-app:${VERSION} .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push your-docker-user/your-app:${VERSION}

    - name: Update Kustomize manifest
      run: |
        sed -i "s|image: your-docker-user/your-app:.*|image: your-docker-user/your-app:${VERSION}|g" k8s/base/deployment.yaml
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add k8s/base/deployment.yaml
        git commit -m "Update image tag to ${VERSION}"
        git push
