name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history in case you want to tag

    - name: Extract version from package.json
      id: pkg
      run: |
        VERSION=$(jq -r .version package.json)
        TAG="${VERSION}-sha.${GITHUB_SHA:0:7}"

    - name: Build Docker image
      run: docker build -t platof/argocd-test-app:${TAG} .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set Git remote to use PAT
      run: git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

    - name: Push Docker image
      run: docker push platof/argocd-test-app:${TAG}

    - name: Update Kustomize manifest
      run: |
        sed -i "s|image: platof/argocd-test-app:.*|image: platof/argocd-test-app:${TAG}|g" k8s/base/deployment.yaml
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add k8s/base/deployment.yaml
        git commit -m "Update image tag to ${VERSION}"
        git push
