name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/base/deployment.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0  # Full history in case you want to tag

    - name: Extract version from package.json
      id: pkg
      run: |
        VERSION=$(jq -r .version package.json)
        SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
        TAG="${VERSION}-sha.${SHORT_SHA}"
        echo "VERSION=$VERSION"
        echo "TAG=$TAG"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t ghcr.io/platof/argocd-test-app:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: docker push ghcr.io/platof/argocd-test-app:latest
